expmt/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'expmt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^story/', include('story.urls', namespace="story")),
    url(r'^tests/', include('tests.urls', namespace="tests")),
    url(r'^admin/', include(admin.site.urls)),
)

projects/urls.py
"""

   Copyright 2014 Joel Compton

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ./exmpt/projects/urls.py

"""

from django.conf.urls import patterns, url

from projects import views

urlpatterns = patterns('',
    #ex: /projects/
    url(r'^$', views.index, name='index'),
    #ex: /projects/3/
    url(r'^(?P<project_id>\d+)/$', views.project, name='project'),
    #ex: /projects/3/edit
    url(r'^(?P<project_id>\d+)/edit/$', views.edit, name='edit'),
    #ex: /projects/3/post
    url(r'^(?P<project_id>\d+)/post/$', views.post, name='post'),
    #ex: /projects/3/delete
    url(r'^(?P<project_id>\d+)/delete/$', views.delete, name='delete'),
    #ex: /projects/3/comment
    url(r'^(?P<project_id>\d+)/comment/$', views.comment, name='comment'),
)

story/urls.py
"""

   Copyright 2014 Joel Compton

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ./exmpt/story/urls.py

"""

from django.conf.urls import patterns, url

from story import views

urlpatterns = patterns('',
    #ex: /story/3/
    url(r'^(?P<story_id>\d+)/$', views.story, name='story'),
    #ex: /story/3/edit
    url(r'^(?P<story_id>\d+)/edit/$', views.edit, name='edit'),
    #ex: /story/3/post
    url(r'^(?P<story_id>\d+)/post/$', views.post, name='post'),
    #ex: /story/3/delete
    url(r'^(?P<story_id>\d+)/delete/$', views.delete, name='delete'),
    #ex: /story/3/comment
    url(r'^(?P<story_id>\d+)/comment/$', views.comment, name='comment'),
)

projects/models.py
"""

   Copyright 2014 Joel Compton

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ./exmpt/projects/models.py

"""

from django.db import models


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=600)
    pub_date = models.DateTimeField()
    up_date = models.DateTimeField()
    complete = models.BooleanField(default=False)
    published = models.BooleanField(default=True)
    author = models.CharField(max_length=100)
    contact_name = models.CharField(max_length=100)
    contact_email = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Pcomment(models.Model):
    project = models.ForeignKey(Project)
    comment = models.CharField(max_length=600)
    pub_date = models.DateField()
    author = models.CharField(max_length=100)

    def __str__(self):
        return self.comment

story/models.py
"""

   Copyright 2014 Joel Compton

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ./exmpt/story/models.py

"""

from django.db import models
from projects.models import Project


# model to represent user stories
# cards are related to projects
# A project will have many cards
class Card(models.Model):
    project = models.ForeignKey(Project)
    story = models.CharField(max_length=600)
    points = models.IntegerField()
    pub_date = models.DateTimeField()
    up_date = models.DateTimeField()
    complete = models.BooleanField(default=False)
    published = models.BooleanField(default=True)
    author = models.CharField(max_length=100)

    def __str__(self):
        return self.story


# model to represent comments on Cards
# a card will have many comments
class Comment(models.Model):
    card = models.ForeignKey(Card)
    comment = models.CharField(max_length=600)
    hours = models.IntegerField(default=0)
    author = models.CharField(max_length=100)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.comment

projects/views.py
"""

   Copyright 2014 Joel Compton

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ./exmpt/projects/views.py

"""
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import datetime
#HttpResponseRedirect
#from django.core.urlresolvers import reverse
#import datetime

from projects.models import Project, Pcomment


# Create your views here.
def index(request):
    project_list = Project.objects.all().order_by('-pub_date')
    context = {'project_list': project_list}
    return render(request, 'projects/index.html', context)


def project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'projects/project.html', {'project': project})


def edit(request, project_id):
    try:
        project = Project.objects.get(pk=project_id)
    except Project.DoesNotExist:
        project = Project(name="project", description="agile project",
            pub_date=datetime.now(), up_date=datetime.now(), author="none",
            contact_name="none", contact_email="none")
        project.save()
    return render(request, 'projects/edit.html', {'project': project})
    #reply = "Edit page has not yet been implemented<br />"
    #reply += "project_id: %s" % project_id
    #return HttpResponse(reply)


def post(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    project.name = request.POST['name']
    project.author = request.POST['author']
    project.contact_name = request.POST['cname']
    project.contact_email = request.POST['cemail']
    project.description = request.POST['description']
    project.up_date = datetime.now()
    check = False
    if 'complete' in request.POST:
        check = True
    project.complete = check
    project.save()
    return HttpResponseRedirect(reverse('projects:project', args=(project_id,)))
    #reply = "Post page has not yet been implemented<br />"
    #reply += "project_id: %s" % project_id
    #return HttpResponse(reply)


def delete(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    project.delete()
    return HttpResponseRedirect(reverse('projects:index'))
    #reply = "Delete page has not yet been implemented<br />"
    #reply += "project_id: %s" % project_id
    #return HttpResponse(reply)


def comment(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    post_author = request.POST['author']
    post_comment = request.POST['comment']
    cur_date = datetime.now()
    com = Pcomment(project=project, comment=post_comment, author=post_author,
        pub_date=cur_date)
    com.save()
    return HttpResponseRedirect(reverse('projects:project', args=(project_id,)))
    reply = "Comment page has not yet been implemented<br />"
    reply += "project_id: %s" % project_id
    return HttpResponse(reply)

projects/templates/projects/edit.html
{% comment %}
<pre>Copyright 2014 Joel Compton

Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

./expmt/projects/templates/projects/edit.html

</pre>
{% endcomment%}

{% include "projects/header.html" %}

<div class="container theme-showcase" role="main">
    <div class="jumbotron">
        <h2>{{ project.name }} edit</h2>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form action="{% url 'projects:post' project.id %}" method="post" id="projectform">
        {% csrf_token %}
            Name: <input type="text" name="name" value="{{ project.name }}"><br />
            Author: <input type="text" name="author" value="{{ project.author }}"><br />
            Contact Name: <input type="text" name="cname" value="{{ project.contact_name }}"><br />
            Contact Email: <input type="text" name="cemail" value="{{ project.contact_email }}"><br />
            Complete: <input type="checkbox" name="complete" {% if project.complete %} checked {% endif %}><br />
            Description: <br />
            <textarea row="4" col="500" name="description" form="projectform">{{ project.description }}</textarea><br />
            <input type="submit" value="Save">
        </form>
    </div>
</div>

projects/templates/projects/header.html
{% comment %}
<pre>Copyright 2014 Joel Compton

Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

./expmt/projects/templates/projects/header.html

</pre>
{% endcomment%}

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<h1><a href="{% url 'projects:index'%}">EXPMT</a></h1>
<h3>Exium Project Management Tool</h3>
<hr />

projects/templates/projects/index.html
{% comment %}
<pre>Copyright 2014 Joel Compton

Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

./expmt/projects/templates/projects/index.html

</pre>
{% endcomment%}

{% include "projects/header.html" %}

<div class="container theme-showcase" role="main">
    <div class="jumbotron">
<h2>Projects</h2>
<form action="{% url 'projects:edit' 9999999 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="New Project">
</form>
{% if project_list %}
	<ul>
	{% for project in project_list %}
		<li><a href="{% url 'projects:project' project.id %}">{{ project.name }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No projects are available.</p>
{% endif %}
</div></div>

projects/templates/projects/project.html
{% comment %}
<pre>Copyright 2014 Joel Compton

Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

./expmt/projects/templates/projects/projects.html

</pre>
{% endcomment%}
{% include "projects/header.html" %}

<div class="container theme-showcase" role="main">
	<div class="jumbotron">
		<h2>Project: {{ project.name }}</h2>
		<form action="{% url 'projects:edit' project.id %}" method="post">
		{% csrf_token %}
		    <input type="submit" value="edit project">
		</form>
		<form action="{% url 'projects:delete' project.id %}" method="post">
		{% csrf_token %}
		    <input type="submit" value="delete project">
		</form>
			<p>Decription: {{ project.description }}</p>
			<p>Published: {{ project.pub_date }}</p>
			<p>Author: {{ project.author }}</p>
			<p>Contact Name: {{ project.contact_name }}</p>
			<p>Contact Email: {{ project.contact_email }}</p>
			<p>Complete:
				{% if project.complete %}
					Yes
				{% else %}
					No
				{% endif %}
			</p>
			<form action="{% url 'story:edit' 9999999 %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="projectid" value="{{ project.id }}">
			<input type="submit" value="new card">
			</form>
		<ul>
			{% for card in project.card_set.all %}
				<li><a href="{% url 'story:story' card.id %}">
				{% if card.complete %}
				<del>
				{% endif %}
				{{ card.story }}
				{% if card.complete %}
				</del>
				{% endif %}
				</a></li>
			{% endfor %}
		</ul>
		<form action="{% url 'projects:comment' project.id %}" method="post" id="commform">
	  	{% csrf_token %}
		<h3>Post comment</h3>
		Author: <input type="text" name="author" value="author"> <br />
		Comment:<br />
		<textarea rows="2" col="500" name="comment" form="commform" maxlength="600"></textarea><br />
		<input type="submit" value="comment">
		<table>
		<col width="200">
		<col width="500">
		<tr><th>User</td><th>Comment</td></tr>
			{% for comment in project.pcomment_set.all %}
			<tr>
				<td>{{ comment.author }} said:<br />
					{{ comment.pub_date }}</td>
				<td>{{ comment.comment }}</td>
			</tr>
			{% endfor %}
		</table>
	</div>
</div>