expmt/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'expmt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^story/', include('story.urls', namespace="story")),
    url(r'^tests/', include('tests.urls', namespace="tests")),
    url(r'^admin/', include(admin.site.urls)),
)

story/urls.py
"""

   Copyright 2014 Joel Compton

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ./exmpt/story/urls.py

"""

from django.conf.urls import patterns, url

from story import views

urlpatterns = patterns('',
    #ex: /story/3/
    url(r'^(?P<story_id>\d+)/$', views.story, name='story'),
    #ex: /story/3/edit
    url(r'^(?P<story_id>\d+)/edit/$', views.edit, name='edit'),
    #ex: /story/3/post
    url(r'^(?P<story_id>\d+)/post/$', views.post, name='post'),
    #ex: /story/3/delete
    url(r'^(?P<story_id>\d+)/delete/$', views.delete, name='delete'),
    #ex: /story/3/comment
    url(r'^(?P<story_id>\d+)/comment/$', views.comment, name='comment'),
)

story/models.py
"""

   Copyright 2014 Joel Compton

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ./exmpt/story/models.py

"""

from django.db import models
from projects.models import Project


# model to represent user stories
# cards are related to projects
# A project will have many cards
class Card(models.Model):
    project = models.ForeignKey(Project)
    story = models.CharField(max_length=600)
    points = models.IntegerField()
    pub_date = models.DateTimeField()
    up_date = models.DateTimeField()
    complete = models.BooleanField(default=False)
    published = models.BooleanField(default=True)
    author = models.CharField(max_length=100)

    def __str__(self):
        return self.story


# model to represent comments on Cards
# a card will have many comments
class Comment(models.Model):
    card = models.ForeignKey(Card)
    comment = models.CharField(max_length=600)
    hours = models.IntegerField(default=0)
    author = models.CharField(max_length=100)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.comment

story/views.py
"""

   Copyright 2014 Joel Compton

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   ./exmpt/story/views.py

"""

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import datetime

from story.models import Card, Comment
from projects.models import Project


# Create your views here.
def story(request, story_id):
    card = get_object_or_404(Card, pk=story_id)
    return render(request, 'story/story.html', {'card': card})
    #reply = "Story page has not yet been implemented<br />"
    #reply += "story_id: %s" % story_id
    #return HttpResponse(reply)


def edit(request, story_id):
    try:
        card = Card.objects.get(pk=story_id)
    except Card.DoesNotExist:
        proj = get_object_or_404(Project, pk=request.POST['projectid'])
        card = Card(project=proj, story="User Story", points=0,
            pub_date=datetime.now(), up_date=datetime.now(), author="author")
        card.save()
    return render(request, 'story/edit.html', {'card': card})
    #reply = "Edit page has not yet been implemented<br />"
    #reply += "story_id: %s" % story_id
    #return HttpResponse(reply)


def post(request, story_id):
    card = get_object_or_404(Card, pk=story_id)
    card.story = request.POST['story']
    card.points = int(request.POST['points'])
    card.author = request.POST['author']
    card.up_date = datetime.now()
    check = False
    if 'complete' in request.POST:
        check = True
    card.complete = check
    card.save()
    project = card.project_id
    return HttpResponseRedirect(reverse('projects:project', args=(project,)))
    #reply = "Post page has not yet been implemented<br />"
    #reply += "story_id: %s" % story_id
    #return HttpResponse(reply)


def delete(request, story_id):
    card = get_object_or_404(Card, pk=story_id)
    project = card.project_id
    card.delete()
    return HttpResponseRedirect(reverse('projects:project', args=(project,)))
    #reply = "Delete page has not yet been implemented<br />"
    #reply += "story_id: %s" % story_id
    #return HttpResponse(reply)


def comment(request, story_id):
    story_card = get_object_or_404(Card, pk=story_id)
    post_author = request.POST['author']
    post_hours = request.POST['hours']
    post_comment = request.POST['comment']
    cur_date = datetime.now()
    com = Comment(card=story_card, comment=post_comment, hours=post_hours,
        author=post_author, pub_date=cur_date)
    com.save()
    return HttpResponseRedirect(reverse('story:story', args=(story_id,)))
    #reply = "Comment page has not yet been implemented<br />"
    #reply += "story_id: %s" % story_id
    #return HttpResponse(reply)

story/templates/story/edit.html
{% comment %}
<pre>Copyright 2014 Joel Compton

Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

./expmt/story/templates/story/edit.html

</pre>
{% endcomment%}
{% include "projects/header.html" %}

<div class="container theme-showcase" role="main">
    <div class="jumbotron">
		<h2>{{ card.story }} edit</h2>
		{% if error_message  %}
		<p><strong>{{ error_message }}</strong></p>
		{% endif %}
		<form action="{% url 'story:post' card.id %}" method="post" id="storeform">
		{% csrf_token %}
			Story: <br />
			<textarea row="4" col="500" name="story" form="storeform" maxlength="600">{{ card.story }}</textarea><br />
			Points: <br />
			<input type="number" name="points" value="{{ card.points }}"><br />
			Author: <br />
			<input type="text" name="author" value="{{ card.author }}"><br />
			Completed:
			<input type="checkbox" name="complete" {% if card.complete %} checked {% endif %}><br />
			<input type="hidden" name="projectid" value="{{ card.project_id }}">
			<input type="submit" value="Save">
		</form>
	</div>
</div>

story/templates/story/story.html
{% comment %}
<pre>Copyright 2014 Joel Compton

Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

./expmt/story/templates/story/story.html

</pre>
{% endcomment%}
{% include "projects/header.html" %}

<div class="container theme-showcase" role="main">
    <div class="jumbotron">
      <h2>User Story</h2>
            <form action="{% url 'story:edit' card.id %}" method="post">
            {% csrf_token %}
              <input type="hidden" name="projectid" value="{{ card.project_id }}">
              <input type="submit" value="edit card">
            </form>
            <form action="{% url 'story:edit' 9999999 %}" method="post">
            {% csrf_token %}
              <input type="hidden" name="projectid" value="{{ card.project_id }}">
              <input type="submit" value="new card">
            </form>
            <form action="{% url 'story:delete' card.id %}" method="post">
            {% csrf_token %}
              <input type="hidden" name="projectid" value="{{ card.project_id }}">
              <input type="submit" value="delete card">
            </form>
      <p>Project: {{ card.project }}</p>
      <p>Story: {{ card.story }}</p>
      <p>Points: {{ card.points }}</p>
      <p>Created: {{ card.pub_date }}</p>
      <p>Author: {{ card.author }}</p>
      <p>Completed: {{ card.complete }}</p>
      <form action="{% url 'tests:edit' 9999999 %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="cardid" value="{{ card.id }}">
			<input type="submit" value="new test">
			</form>
      <ul>
			{% for test in card.test_set.all %}
				<li><a href="{% url 'tests:test' test.id %}">
				{% if test.accepted %}
				<del>
				{% endif %}
				{{ test.acceptance }}
				{% if test.accepted %}
				</del>
				{% endif %}
				</a></li>
			{% endfor %}
		</ul>
              <form action="{% url 'story:comment' card.id %}" method="post" id="commform">
	  	{% csrf_token %}
		<h3>Post comment</h3>
		Author: <input type="text" name="author" value="author"> <br />
		Hours: <input type="number" name="hours" value="0"><br />
		Comment:<br />
		<textarea rows="2" col="500" name="comment" form="commform" maxlength="600"></textarea><br />
		<input type="submit" value="comment">
	 		<table>
		<col width="200">
		<col width="500">
		<col width="100">
			<tr><th>User</th><th>Comment</th><th>Hours</th></tr>
			{% for comment in card.comment_set.all %}
			<tr>
				<td>{{ comment.author }} <br />
					{{ comment.pub_date }}</td>
				<td>{{ comment.comment }}</td>
				<td>{{ comment.hours }}</td>
			</tr>
			{% endfor %}
		</table>
		
	  </form>

	</div>
</div>